language: r
sudo: required
dist: xenial
r:
  - release
  - devel
  - oldrel
cache: 
  - packages
  - ccache
addons:
  apt:
    packages:
     - libgdal-dev
     - libproj-dev 
     - libgeos-dev
     - libudunits2-dev 
warnings_are_errors: true
r_packages:
  - covr
after_success:
  - R -q -e 'covr::codecov(quiet = FALSE)'