language: r
sudo: required
dist: xenial
r:
  - release
  - devel
  - oldrel
cache: 
  - packages
  - ccache
addons:
  apt:
    packages:
     - libgdal-dev
     - libproj-dev 
     - libgeos-dev
     - libudunits2-dev 
before_install:
  - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nVER=\nCCACHE=ccache\nCC=$(CCACHE) gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE) g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars
warnings_are_errors: true
r_packages:
  - covr
after_success:
  - R -q -e 'covr::codecov(quiet = FALSE)'