language: r
sudo: required
dist: xenial
#cache:
#  - packages
#r:
#  - devel
#  - release
#  - oldrel
jobs:
  include:
  - r: devel
  - r: release
    cache:
      - packages
  - r: oldrel
    cache:
      - packages

addons:
  apt:
    packages:
     - libgdal-dev
     - libproj-dev 
     - libgeos-dev
     - libudunits2-dev 
warnings_are_errors: true
r_packages:
  - SpatialPosition
  - knitr
  - rmarkdown
  - tinytest
  - covr
  - rgdal
after_success:
  - R -q -e 'covr::codecov(quiet = FALSE)'